# action.yaml
name: 'Custom GitHub Action'
description: ''
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Getting chart
      id: get-chart
      run: python getchart.py
      shell: bash