# action.yaml
name: 'Custom GitHub Action'
description: ''
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Change ImageMagick policy to allow pdf->png conversion.
      run: sudo sed -i 's/^.*policy.*coder.*none.*PDF.*//' /etc/ImageMagick-6/policy.xml
      shell: bash
    - name: Install Ghostscript
      run: sudo apt-get update && sudo apt-get install ghostscript -y
      shell: bash
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Getting chart
      id: get-chart
      run: python getchart.py
      shell: bash
    - name: Commit results
      run: |
          git add latest.gif latest.txt
          git config --global user.name 'Angie Garz'
          git config --global user.email 'angie.m.garz@gmail.com'
          git commit -m "New ice chart" || echo "No changes to commit"
          git push || echo "No changes to commit"
      shell: bash
