# .github/workflows/test_action.yaml
name: Test Action
on: [push]
permissions:
  contents: write

jobs:
  get-ice-chart:
    runs-on: ubuntu-latest
    name: Gets the latest ice chart
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get ice chart
        id: get_chart
        uses: ./ # Uses an action in the root directory
      - name: Commit results
        run: |
          git add latest.gif latest.txt
	  git config --global user.name 'Angie Garz'
          git config --global user.email 'angie.m.garz@gmail.com'
          git commit -am "New ice chart"
          git push
