# .github/workflows/test_action.yaml
name: Test Action
on: [push]

jobs:
  get-ice-chart:
    runs-on: ubuntu-latest
    name: Gets the latest ice chart
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get ice chart
        id: get_square
        uses: ./ # Uses an action in the root directory
